library(RColorBrewer)

A_bmm <- read.delim("~/Desktop/A_ent 2/A_bmm.txt")
View(A_bmm)
cov(A_bmm)
cor(A_bmm)
coul=colorRampPalette(brewer.pal(8, "PiYG"))(25)
heatmap(cor(A_bmm), col=coul, Rowv = NA , Colv = NA, main = "A_bmm")

A_bru <- read.delim("~/Desktop/A_ent 2/A_bru.txt")
View(A_bru)
cov(A_bru)
cor(A_bru)
coul=colorRampPalette(brewer.pal(8, "YlOrRd"))(25)
heatmap(cor(A_bru), col=coul, Rowv = NA , Colv = NA, main = "A_bru")

A_crf <- read.delim("~/Desktop/A_ent 2/A_crf.txt")
View(A_crf)
cov(A_crf)
cor(A_crf)
coul=colorRampPalette(brewer.pal(8, "YlOrBr"))(25)
heatmap(cor(A_crf), col=coul, Rowv = NA , Colv = NA, main = "A_crf")

A_ent <- read.delim("~/Desktop/A_ent 2/A_ent.txt")
View(A_ent)
cov(A_ent)
cor(A_ent)
coul=colorRampPalette(brewer.pal(8, "YIGnBu"))(25)
heatmap(cor(A_ent), col=coul, Rowv = NA , Colv = NA, main = "A_ent")

A_fmm <- read.delim("~/Desktop/A_ent 2/A_fmm.txt")
View(A_fmm)
cov(A_fmm)
cor(A_fmm)
coul=colorRampPalette(brewer.pal(8, "YlGn"))(25)
heatmap(cor(A_fmm), col=coul, Rowv = NA , Colv = NA, main = "A_fmm")

A_fmm <- read.delim("~/Desktop/A_ent 2/A_pretrain.txt")
View(A_pretrain)
cov(A_pretrain)
cor(A_pretrian)
coul=colorRampPalette(brewer.pal(8, "Greys"))(25)
heatmap(cor(A_pretrain), col=coul, Rowv = NA , Colv = NA, main = "A_pretrain")


A_fmm <- read.delim("~/Desktop/A_ent 2/F_bmm.txt")
View(F_bmm)
cov(F_bmm)
cor(F_bmm)
coul=colorRampPalette(brewer.pal(8, "GnBu"))(25)
heatmap(cor(F_bmm), col=coul, Rowv = NA , Colv = NA, main = "F_bmm")


F_bru <- read.delim("~/Desktop/A_ent 2/F_bru.txt")
View(F_bru)
cov(F_bru)
cor(F_bru)
coul=colorRampPalette(brewer.pal(8, "Reds"))(25)
heatmap(cor(F_bru), col=coul, Rowv = NA , Colv = NA, main = "F_bru")

F_crf <- read.delim("~/Desktop/A_ent 2/F_crf.txt")
View(F_crf)
cov(F_crf)
cor(F_crf)
coul=colorRampPalette(brewer.pal(8, "Purples"))(25)
heatmap(cor(F_crf), col=coul, Rowv = NA , Colv = NA, main = "F_crf")

F_ent <- read.delim("~/Desktop/A_ent 2/F_ent.txt")
View(F_ent)
cov(F_ent)
cor(F_ent)
coul=colorRampPalette(brewer.pal(8, "RdPu"))(25)
heatmap(cor(F_ent), col=coul, Rowv = NA , Colv = NA, main = "F_ent")

F_fmm <- read.delim("~/Desktop/A_ent 2/F_fmm.txt")
View(F_fmm)
cov(F_fmm)
cor(F_fmm)
coul=colorRampPalette(brewer.pal(8, "Purples"))(25)
heatmap(cor(F_fmm), col=coul, Rowv = NA , Colv = NA, main = "F_fmm")

F_pretrain <- read.delim("~/Desktop/A_ent 2/F_pretrain.txt")
View(F_pretrain)
cov(F_pretrain)
cor(F_pretrain)
coul=colorRampPalette(brewer.pal(8, "PuBu"))(25)
heatmap(cor(F_pretrain), col=coul, Rowv = NA , Colv = NA, main = "F_pretrain")

V_bmm <- read.delim("~/Desktop/A_ent 2/V_bmm.txt")
View(V_bmm)
cov(V_bmm)
cor(V_bmm)
coul=colorRampPalette(brewer.pal(8, "BuGn"))(25)
heatmap(cor(V_bmm), col=coul, Rowv = NA , Colv = NA, main = "V_bmm")

V_bru <- read.delim("~/Desktop/A_ent 2/V_bru.txt")
View(V_bru)
cov(V_bru)
cor(V_bru)
coul=colorRampPalette(brewer.pal(8, "Blues"))(25)
heatmap(cor(V_bru), col=coul, Rowv = NA , Colv = NA, main = "V_bru")

V_crf <- read.delim("~/Desktop/A_ent 2/V_crf.txt")
View(V_crf)
cov(V_crf)
cor(V_crf)
coul=colorRampPalette(brewer.pal(8, "Oranges"))(25)
heatmap(cor(V_crf), col=coul, Rowv = NA , Colv = NA, main = "V_crf")

V_ent <- read.delim("~/Desktop/A_ent 2/V_ent.txt")
View(V_ent)
cov(V_ent)
cor(V_ent)
coul=colorRampPalette(brewer.pal(8, "BuPu"))(25)
heatmap(cor(V_ent), col=coul, Rowv = NA , Colv = NA, main = "V_ent")

V_fmm <- read.delim("~/Desktop/A_ent 2/V_fmm.txt")
View(V_fmm)
cov(V_fmm)
cor(V_fmm)
coul=colorRampPalette(brewer.pal(8, "Reds"))(25)
heatmap(cor(V_fmm), col=coul, Rowv = NA , Colv = NA, main = "V_fmm")

V_pretrain <- read.delim("~/Desktop/A_ent 2/V_pretrain.txt")
View(V_pretrain)
cov(V_pretrain)
cor(V_pretrain)
coul=colorRampPalette(brewer.pal(8, "YlGn"))(25)
heatmap(cor(V_pretrain),  col=coul, Rowv = NA , Colv = NA, main = "V_pretrain")
